version: '3'
services:
        bp_flask_server:
                build:
                        context: .
                ports:
                        - 5000:5000
                        - 5001:5001
